-- GRIDOPT - apply the whole database setup in one run.
-- Generated by concatenating schema.sql + seed.sql. Run this first, then
-- run verify.sql separately to read the security assertions.
--
-- Both halves are idempotent: re-running changes nothing and duplicates nothing.

-- ===================== schema.sql =====================
-- GRIDOPT - Supabase schema for the network dataset.
--
-- Scope: stations and transmission lines only. No authentication, no user
-- tables, no application state. The existing FastAPI login screen and every
-- solver are untouched by this file.
--
-- Source of truth remains data/transmition_lines.csv.csv. These tables are
-- seeded FROM that file (see generate_seed.py -> seed.sql); the CSV is never
-- written to, renamed, or derived from the database.
--
-- Safe to re-run: every statement is idempotent.
--
-- Run order:
--   1. schema.sql   (this file)
--   2. seed.sql     (generated from the CSV)
--   3. verify.sql   (grants + RLS assertions)

begin;

-- ---------------------------------------------------------------------------
-- stations
--
-- One row per distinct station name in the CSV. `name` is the natural key: the
-- CSV identifies stations by name and the API returns them by name, so the
-- unique constraint on it is what prevents duplicate station records.
-- ---------------------------------------------------------------------------
create table if not exists public.stations (
  id          bigint generated always as identity primary key,
  name        text        not null,
  type        text        not null,
  latitude    double precision not null,
  longitude   double precision not null,
  created_at  timestamptz not null default now(),

  constraint stations_name_key unique (name),
  constraint stations_latitude_range  check (latitude  between  -90 and  90),
  constraint stations_longitude_range check (longitude between -180 and 180)
);

comment on table  public.stations is 'Stations derived from the transmission-line CSV. Seeded, not authored.';
comment on column public.stations.name is 'Natural key. Matches the Source/Destination values in the CSV exactly.';

-- ---------------------------------------------------------------------------
-- transmission_lines
--
-- One row per CSV data row. Endpoints are foreign keys into stations rather
-- than repeated names, so a station exists exactly once no matter how many
-- lines touch it.
--
-- `csv_row` keeps provenance: it is the 1-based line number in the CSV the row
-- came from, so any value here can be traced back to the file it came from.
-- ---------------------------------------------------------------------------
create table if not exists public.transmission_lines (
  id              bigint generated always as identity primary key,
  source_id       bigint not null references public.stations (id) on delete restrict,
  destination_id  bigint not null references public.stations (id) on delete restrict,
  type            text   not null,
  distance_km     double precision not null,
  voltage_kv      double precision not null,
  capacity_mw     double precision not null,
  loss_percent    double precision not null,
  energy_loss_mw  double precision not null,
  csv_row         integer not null,
  created_at      timestamptz not null default now(),

  constraint transmission_lines_no_self_loop check (source_id <> destination_id),
  constraint transmission_lines_distance_positive check (distance_km    > 0),
  constraint transmission_lines_voltage_positive  check (voltage_kv     > 0),
  constraint transmission_lines_capacity_positive check (capacity_mw   >= 0),
  constraint transmission_lines_energy_loss_positive check (energy_loss_mw >= 0),
  constraint transmission_lines_loss_percent_range check (loss_percent between 0 and 100)
);

-- A line is undirected: A->B and B->A are the same physical circuit. Indexing
-- the *unordered* pair is what stops the same line being stored twice.
create unique index if not exists transmission_lines_pair_key
  on public.transmission_lines (
    least(source_id, destination_id),
    greatest(source_id, destination_id)
  );

create index if not exists transmission_lines_source_idx      on public.transmission_lines (source_id);
create index if not exists transmission_lines_destination_idx on public.transmission_lines (destination_id);

comment on table  public.transmission_lines is 'Transmission lines, one row per CSV data row. Undirected: the pair is unique regardless of direction.';
comment on column public.transmission_lines.csv_row is 'Provenance: 1-based line number in the source CSV.';

-- ---------------------------------------------------------------------------
-- A read-only join that speaks names, the way the API does.
--
-- security_invoker = true is essential: without it the view would run with the
-- privileges of its owner and would hand out rows that the caller's own RLS
-- policies deny. With it, the base-table policies below still apply.
-- ---------------------------------------------------------------------------
create or replace view public.transmission_lines_expanded
with (security_invoker = true) as
select
  l.id,
  s.name  as source,
  d.name  as destination,
  l.type,
  l.distance_km,
  l.voltage_kv,
  l.capacity_mw,
  l.loss_percent,
  l.energy_loss_mw,
  l.csv_row
from public.transmission_lines l
join public.stations s on s.id = l.source_id
join public.stations d on d.id = l.destination_id;

-- ===========================================================================
-- SECURITY
--
-- Two independent gates, because RLS alone is not sufficient: PostgREST can
-- only reach a table if the role has been GRANTed on it, and a policy can only
-- filter rows the grant already allows. Both are set explicitly below.
--
-- Posture: the Data API is closed. Nothing in this application reads these
-- tables from the browser - FastAPI is the only consumer, and it connects with
-- the service_role key, which bypasses RLS by design. So the least privilege
-- that the application actually requires from `anon` and `authenticated` is
-- none at all, and that is what is granted.
--
-- Opening read access later is a deliberate, reviewable change: see the
-- OPTIONAL block at the end of this file.
-- ===========================================================================

alter table public.stations            enable row level security;
alter table public.transmission_lines  enable row level security;

-- FORCE also subjects the table owner to its policies. Without it, anything
-- connecting as the owner silently skips every policy below.
alter table public.stations            force row level security;
alter table public.transmission_lines  force row level security;

-- Gate 1: grants. Remove the blanket privileges Supabase hands the API roles
-- on new objects in `public`.
revoke all on public.stations                    from anon, authenticated, public;
revoke all on public.transmission_lines          from anon, authenticated, public;
revoke all on public.transmission_lines_expanded from anon, authenticated, public;

-- The same, for anything added to this schema later. Without this, the next
-- table created here starts out reachable again.
alter default privileges in schema public revoke all on tables    from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

-- Gate 2: policies. RLS denies everything by default once enabled, so the
-- absence of a permissive policy for anon/authenticated IS the deny rule.
-- These two exist to make the intent explicit and self-documenting rather
-- than implied by omission, and to fail loudly if a grant is ever restored
-- by accident.
drop policy if exists stations_no_public_access on public.stations;
create policy stations_no_public_access
  on public.stations
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists transmission_lines_no_public_access on public.transmission_lines;
create policy transmission_lines_no_public_access
  on public.transmission_lines
  for all
  to anon, authenticated
  using (false)
  with check (false);

commit;

-- ===========================================================================
-- OPTIONAL - read-only network data over the Data API.
--
-- Apply this ONLY if the browser is ever given the publishable (anon) key and
-- has to read the network directly. It grants SELECT and nothing else: no
-- insert, update or delete, on either role. Today the application does not
-- need it, so it is left unapplied.
--
--   grant select on public.stations                    to anon, authenticated;
--   grant select on public.transmission_lines          to anon, authenticated;
--   grant select on public.transmission_lines_expanded to anon, authenticated;
--
--   drop policy if exists stations_no_public_access on public.stations;
--   create policy stations_read_only
--     on public.stations for select to anon, authenticated using (true);
--
--   drop policy if exists transmission_lines_no_public_access on public.transmission_lines;
--   create policy transmission_lines_read_only
--     on public.transmission_lines for select to anon, authenticated using (true);
--
-- Note what this would mean: the network becomes world-readable to anyone
-- holding the publishable key, which is public by definition. That is a
-- disclosure decision about the dataset, not a technical one.
-- ===========================================================================

-- ====================== seed.sql ======================
-- GRIDOPT seed data - GENERATED, do not edit by hand.
-- Source: transmition_lines.csv.csv
-- Regenerate with: .venv\Scripts\python.exe supabase/generate_seed.py
-- Contents: 26 stations, 38 transmission lines.
--
-- Idempotent: stations upsert on name, lines on the unordered endpoint
-- pair, so re-running changes nothing and duplicates nothing.

begin;

insert into public.stations (name, type, latitude, longitude) values
  ('Belagavi Substation', 'substation', 15.8497, 74.4977),
  ('Bellary Thermal Power Station', 'thermal', 15.1421, 76.8747),
  ('Bengaluru (Kadabagere/Hoody) Substation', 'substation', 12.9716, 77.5946),
  ('Chitradurga Wind Cluster', 'wind', 14.23, 76.4),
  ('Davangere Substation', 'substation', 14.4644, 75.9218),
  ('Gadag Wind-Solar Hybrid Cluster', 'wind', 14.99, 75.63),
  ('Gerusoppa Power House', 'hydro', 14.205, 74.652),
  ('Hassan Substation', 'substation', 13.0072, 76.1004),
  ('Hubballi-Dharwad Substation', 'substation', 15.3647, 75.124),
  ('Kadra Power House', 'hydro', 14.802, 74.522),
  ('Kaiga Nuclear Power Station', 'nuclear', 14.864, 74.439),
  ('Kalaburagi Substation', 'substation', 17.3297, 76.8343),
  ('Kappatagudda Wind Cluster', 'wind', 15.35, 75.65),
  ('Kodasalli Power House', 'hydro', 14.848, 74.555),
  ('Linganamakki Dam Power House', 'hydro', 14.205, 74.833),
  ('Mangaluru Substation', 'substation', 12.9141, 74.856),
  ('Mysuru Substation', 'substation', 12.2958, 76.6394),
  ('Nagjhari Power House', 'hydro', 14.85, 74.605),
  ('Pavagada Solar Park (Shakti Sthala)', 'solar', 14.1, 77.28),
  ('Raichur Thermal Power Station', 'thermal', 16.2274, 77.3565),
  ('Sharavathy Generating Station', 'hydro', 14.228, 74.793),
  ('Shivamogga Substation', 'substation', 13.9299, 75.5681),
  ('Supa Dam Power House', 'hydro', 14.95, 74.68),
  ('Tumakuru Substation', 'substation', 13.3379, 77.1173),
  ('Varahi Underground Power House', 'hydro', 13.554, 74.933),
  ('Yermarus Thermal Power Station', 'thermal', 16.1913, 77.4363)
on conflict (name) do update set
  type      = excluded.type,
  latitude  = excluded.latitude,
  longitude = excluded.longitude;

insert into public.transmission_lines (
  source_id, destination_id, type, distance_km, voltage_kv,
  capacity_mw, loss_percent, energy_loss_mw, csv_row
)
select
  s.id, d.id, v.type, v.distance_km, v.voltage_kv,
  v.capacity_mw, v.loss_percent, v.energy_loss_mw, v.csv_row
from (values
  ('Belagavi Substation'::text, 'Supa Dam Power House'::text, 'substation'::text, 101.933::double precision, 110.0::double precision, 1353.809::double precision, 2.243::double precision, 30.366::double precision, 2::integer),
  ('Bellary Thermal Power Station', 'Chitradurga Wind Cluster', 'thermal', 113.549, 66.0, 1700.0, 2.498, 42.466, 3),
  ('Bellary Thermal Power Station', 'Pavagada Solar Park (Shakti Sthala)', 'thermal', 123.81, 220.0, 1700.0, 2.724, 46.308, 4),
  ('Bengaluru (Kadabagere/Hoody) Substation', 'Mysuru Substation', 'substation', 128.017, 220.0, 810.983, 2.816, 22.837, 5),
  ('Chitradurga Wind Cluster', 'Davangere Substation', 'wind', 57.733, 66.0, 550.0, 1.27, 6.985, 6),
  ('Chitradurga Wind Cluster', 'Pavagada Solar Park (Shakti Sthala)', 'wind', 95.971, 66.0, 550.0, 2.111, 11.611, 7),
  ('Chitradurga Wind Cluster', 'Shivamogga Substation', 'wind', 95.728, 66.0, 550.0, 2.106, 11.583, 8),
  ('Davangere Substation', 'Gadag Wind-Solar Hybrid Cluster', 'substation', 66.336, 66.0, 1490.929, 1.459, 21.753, 9),
  ('Davangere Substation', 'Shivamogga Substation', 'substation', 70.613, 220.0, 1229.736, 1.553, 19.098, 10),
  ('Gadag Wind-Solar Hybrid Cluster', 'Kappatagudda Wind Cluster', 'wind', 40.088, 66.0, 300.0, 0.882, 2.646, 11),
  ('Gerusoppa Power House', 'Sharavathy Generating Station', 'hydro', 15.412, 220.0, 240.0, 0.339, 0.814, 12),
  ('Hassan Substation', 'Mysuru Substation', 'substation', 98.373, 220.0, 252.567, 2.164, 5.466, 13),
  ('Hubballi-Dharwad Substation', 'Belagavi Substation', 'substation', 86.065, 220.0, 1680.508, 1.893, 31.812, 14),
  ('Hubballi-Dharwad Substation', 'Supa Dam Power House', 'substation', 66.311, 110.0, 1333.046, 1.459, 19.449, 15),
  ('Kadra Power House', 'Gerusoppa Power House', 'hydro', 67.843, 110.0, 150.0, 1.493, 2.24, 16),
  ('Kadra Power House', 'Kaiga Nuclear Power Station', 'hydro', 11.275, 110.0, 150.0, 0.248, 0.372, 17),
  ('Kaiga Nuclear Power Station', 'Kodasalli Power House', 'nuclear', 12.594, 110.0, 880.0, 0.277, 2.438, 18),
  ('Kalaburagi Substation', 'Yermarus Thermal Power Station', 'substation', 141.886, 220.0, 1373.424, 3.121, 42.865, 19),
  ('Kappatagudda Wind Cluster', 'Hubballi-Dharwad Substation', 'wind', 56.424, 66.0, 250.0, 1.241, 3.103, 20),
  ('Kodasalli Power House', 'Kadra Power House', 'hydro', 6.225, 110.0, 120.0, 0.137, 0.164, 21),
  ('Linganamakki Dam Power House', 'Gerusoppa Power House', 'hydro', 19.511, 66.0, 55.0, 0.429, 0.236, 22),
  ('Linganamakki Dam Power House', 'Varahi Underground Power House', 'hydro', 73.188, 66.0, 55.0, 1.61, 0.886, 23),
  ('Mangaluru Substation', 'Hassan Substation', 'substation', 135.243, 220.0, 307.544, 2.975, 9.149, 24),
  ('Mysuru Substation', 'Tumakuru Substation', 'substation', 126.934, 220.0, 829.625, 2.793, 23.171, 25),
  ('Nagjhari Power House', 'Kadra Power House', 'hydro', 10.397, 110.0, 900.0, 0.229, 2.061, 26),
  ('Nagjhari Power House', 'Kodasalli Power House', 'hydro', 5.379, 110.0, 900.0, 0.118, 1.062, 27),
  ('Pavagada Solar Park (Shakti Sthala)', 'Tumakuru Substation', 'solar', 86.545, 220.0, 2050.0, 1.904, 39.032, 28),
  ('Raichur Thermal Power Station', 'Bellary Thermal Power Station', 'thermal', 131.24, 220.0, 1720.0, 2.887, 49.656, 29),
  ('Raichur Thermal Power Station', 'Kalaburagi Substation', 'thermal', 134.588, 220.0, 1720.0, 2.961, 50.929, 30),
  ('Raichur Thermal Power Station', 'Yermarus Thermal Power Station', 'thermal', 9.419, 220.0, 1720.0, 0.207, 3.56, 31),
  ('Sharavathy Generating Station', 'Linganamakki Dam Power House', 'hydro', 5.013, 66.0, 1035.0, 0.11, 1.138, 32),
  ('Shivamogga Substation', 'Varahi Underground Power House', 'substation', 80.329, 220.0, 700.693, 1.767, 12.381, 33),
  ('Supa Dam Power House', 'Kodasalli Power House', 'hydro', 17.58, 110.0, 100.0, 0.387, 0.387, 34),
  ('Supa Dam Power House', 'Nagjhari Power House', 'hydro', 13.733, 110.0, 100.0, 0.302, 0.302, 35),
  ('Tumakuru Substation', 'Bengaluru (Kadabagere/Hoody) Substation', 'substation', 65.802, 220.0, 1601.359, 1.448, 23.188, 36),
  ('Tumakuru Substation', 'Hassan Substation', 'substation', 116.077, 220.0, 1143.061, 2.554, 29.194, 37),
  ('Varahi Underground Power House', 'Mangaluru Substation', 'hydro', 71.64, 220.0, 460.0, 1.576, 7.25, 38),
  ('Yermarus Thermal Power Station', 'Bellary Thermal Power Station', 'thermal', 131.248, 220.0, 1600.0, 2.887, 46.192, 39)
) as v (
  source, destination, type, distance_km, voltage_kv,
  capacity_mw, loss_percent, energy_loss_mw, csv_row
)
join public.stations s on s.name = v.source
join public.stations d on d.name = v.destination
on conflict (least(source_id, destination_id), greatest(source_id, destination_id))
do update set
  type           = excluded.type,
  distance_km    = excluded.distance_km,
  voltage_kv     = excluded.voltage_kv,
  capacity_mw    = excluded.capacity_mw,
  loss_percent   = excluded.loss_percent,
  energy_loss_mw = excluded.energy_loss_mw,
  csv_row        = excluded.csv_row;

-- Fail the transaction if the row counts do not match the CSV.
do $$
declare
  station_count int;
  line_count    int;
begin
  select count(*) into station_count from public.stations;
  select count(*) into line_count    from public.transmission_lines;
  if station_count <> 26 then
    raise exception 'expected 26 stations, found %', station_count;
  end if;
  if line_count <> 38 then
    raise exception 'expected 38 transmission lines, found %', line_count;
  end if;
end $$;

commit;

